#!/bin/bash
echo 'This installer will set up ViTaMIn and all its dependencies'
echo "ViTaMIn needs to install csh, biopython, matplotlib, pymol and fort77 from Ubuntu repository."
echo 'Modeller key is not provided and you may have to request one at https://salilab.org/modeller/registration.html'
sleep 2s

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

wget https://salilab.org/modeller/9.16/modeller_9.16-1_amd64.deb

echo -n 'If you already have a license, please insert it now:'
read modkey

echo 'Installing MODELLER'
sudo env KEY_MODELLER=$modkey dpkg -i modeller_9.16-1_amd64.deb && rm modeller_9.16-1_amd64.deb



sudo apt-get update
sudo apt-get install csh python-biopython python-gobject python-gi-cairo python-matplotlib pymol lsyncd fort77 -y

mkdir $HOME/Vitamin



mv Vitamin.tar.gz $HOME/Vitamin
mv README $HOME/Vitamin/.src/README
chmod +x vitamin
sudo mv vitamin /usr/local/bin
cd $HOME/Vitamin
tar -xvf Vitamin.tar.gz && rm Vitamin.tar.gz


cd .src/
cd procheck

chmod +x procomp.scr
./procomp.scr

mv $HOME/Vitamin/vitamin.desktop $HOME/.local/share/applications/


if grep -Fq 'alias procheck' ~/.bashrc
then
echo 'Procheck already in bash. Skipping this step.'
else
echo "export VITAMIN_HOME='$HOME/Vitamin/'" >> ~/.bashrc
echo "alias procheck='$HOME/Vitamin/src/procheck/procheck.scr'" >> ~/.bashrc
echo "export prodir='$HOME/Vitamin/src/procheck'" >> ~/.bashrc
fi



bash
sudo rm -r $DIR
cd
